version: '2'

services:
  web:
    image: nginx:1.13-alpine
    ports:
      - "8080:80"
    volumes_from:
      - gallery:ro
    links:
      - gallery:app-container
    restart: always

  gallery:
    image: gallery
    links:
      - postgres:postgres
    environment:
      # Database connection
      DATABASE_DRIVER: pgsql
      DATABASE_HOST: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: gallery
      #
      # Admin panel
      ADMIN_USER: login # TODO update
      ADMIN_PASSWORD: password # TODO update
      #
      # Gallery
      PAGENAME: Gallery by padow # TODO update
      TITLE: Gallery # TODO update
      SUBTITLE: mypics # TODO update
      CONTACT: p4d0w7@gmail.com # TODO update
    volumes:
      # The place where your galleries are stored on the host
      - ./galleries:/var/www/html/galleries # TODO replace with your galleries folder
      # The place where extra assets (aka bio page) are stores on your host
      - ./uploads:/var/www/html/uploads # TODO replace with your photos folder
    restart: always

  postgres:
    image: postgres:9-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    #   PGDATA: /var/lib/postgresql/data/pgdata # TODO uncomment for persistent storage
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data/pgdata
    restart: always
