version: '2'

services:
  web:
    image: nginx:1.13-alpine
    ports:
      - "8080:80"
    volumes_from:
      - gallery:ro
    links:
      - gallery:app-container
    restart: always

  gallery:
    image: gallery
    links:
      - postgres:postgres
    volumes:
      - ./config:/var/www/html/config:ro # TODO replace with your config folder
      - ./photos:/var/www/html/photos # TODO replace with your photos folder
    restart: always

  # {
  # 	"sql":{
  # 		"_comments":"choose `sqlite3`, `pgsql` or `mysql` as driver",
  # 		"driver":"pgsql",
  # 		"host":"postgres",
  # 		"user":"postgres",
  # 		"password":"postgres",
  # 		"database":"gallery"
  # 	}
  # }
  postgres:
    image: postgres:9-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    #   PGDATA: /var/lib/postgresql/data/pgdata # TODO uncomment for persistent storage
    # volumes:
    #   - ./data/db:/var/lib/postgresql/data/pgdata
    restart: always
